### ISSUE TITLE
Cosmetic to-do

### ISSUE THREAD

**Issue by limppa** [limppa/avalon#1]
- [x] - Fix the "A valon" kerning
- [ ] - Improve scoreboard
- [ ] - Improve "Two fails required" antialiasing
- [ ] - "Two fails required" has a hole after quest marker has passed it
- [ ] - Border for the game board?

**Comment by EmilImmonen** [comment]
[ ] - Add clear indication which phase the game is in
